version: "3.8"

services:
  api:
    image: fast-api:base
    working_dir: /base-api
    build:
      dockerfile: docker/Dockerfile.local
    ports:
      - 8000:8000
    volumes:
      - ./app:/base-api/app
