FROM python:3.12-slim-bullseye

RUN apt-get update && apt-get install -y libmagic-dev

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Copy the application into the container.
COPY . /base-api

# Install the application dependencies.
WORKDIR /base-api
RUN uv sync --frozen --no-cache

# Run the application.
CMD ["uv", "run", "uvicorn", "app.main:app", "--reload", "--port", "8000", "--host", "0.0.0.0"]
