FROM python:3.12-slim-bullseye

RUN apt-get update && apt-get install -y libmagic-dev

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# Copy the application into the container.
COPY . /app

# Install the application dependencies.
WORKDIR /app
RUN uv sync --frozen --no-cache

# Run the application.
CMD ["uv", "run", "fastapi", "run", "app/main.py", "--port", "8000"]
